steps:
  - label: ":docker: Build and Run Tests"
    commands:
      - pwd
      - ls -la
      - docker build -t pytest-bdd:latest .
      - docker images
  - label: "run image"
    commands:
      - docker run pytest-bdd:latest
    agents:
      queue: "linux-small"