steps:
  - label: ":docker: Build and Run Tests"
    commands:
      - pwd
      - ls -la
      - docker build -t vaishali0207/pytest-bdd:latest .
      - docker push vaishali0207/pytest-bdd:latest
      - docker images
  - wait

  - label: "run image"
    commands:
      - docker run vaishali0207/pytest-bdd:latest
    agents:
      queue: "linux-small"